2020-07-09 12:25:43,252 > INFO > 
 =================== Starting Airwave Agent ======================== 

2020-07-09 12:25:43,252 > INFO > Starting Airwave Agent...
2020-07-09 12:25:44,703 > INFO > Login success
2020-07-09 12:25:44,703 > INFO > Collecting amp status... 
2020-07-09 12:25:44,977 > INFO > Collecting amp status Success.....
2020-07-09 12:25:45,513 > INFO > Post accepted by server
2020-07-09 12:25:45,514 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:26:45,514 > INFO > Collecting amp status... 
2020-07-09 12:26:45,820 > INFO > Collecting amp status Success.....
2020-07-09 12:26:46,326 > INFO > Post accepted by server
2020-07-09 12:26:46,327 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:27:46,328 > INFO > Collecting amp status... 
2020-07-09 12:27:46,639 > INFO > Collecting amp status Success.....
2020-07-09 12:27:47,145 > INFO > Post accepted by server
2020-07-09 12:27:47,146 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:28:47,147 > INFO > Collecting amp status... 
2020-07-09 12:28:47,444 > INFO > Collecting amp status Success.....
2020-07-09 12:28:47,950 > INFO > Post accepted by server
2020-07-09 12:28:47,951 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:29:47,951 > INFO > Collecting amp status... 
2020-07-09 12:29:48,249 > INFO > Collecting amp status Success.....
2020-07-09 12:29:48,765 > INFO > Post accepted by server
2020-07-09 12:29:48,765 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:30:48,766 > INFO > Collecting amp status... 
2020-07-09 12:30:49,041 > INFO > Collecting amp status Success.....
2020-07-09 12:30:49,550 > INFO > Post accepted by server
2020-07-09 12:30:49,550 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:31:49,550 > INFO > Collecting amp status... 
2020-07-09 12:31:49,819 > INFO > Collecting amp status Success.....
2020-07-09 12:31:50,344 > INFO > Post accepted by server
2020-07-09 12:31:50,345 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:32:50,346 > INFO > Collecting amp status... 
2020-07-09 12:32:50,654 > INFO > Collecting amp status Success.....
2020-07-09 12:32:51,154 > INFO > Post accepted by server
2020-07-09 12:32:51,155 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:33:51,155 > INFO > Collecting amp status... 
2020-07-09 12:33:51,440 > INFO > Collecting amp status Success.....
2020-07-09 12:33:51,946 > INFO > Post accepted by server
2020-07-09 12:33:51,946 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:34:51,946 > INFO > Collecting amp status... 
2020-07-09 12:34:52,239 > INFO > Collecting amp status Success.....
2020-07-09 12:34:52,765 > INFO > Post accepted by server
2020-07-09 12:34:52,765 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:35:52,766 > INFO > Collecting amp status... 
2020-07-09 12:35:53,073 > INFO > Collecting amp status Success.....
2020-07-09 12:35:54,433 > INFO > Post accepted by server
2020-07-09 12:35:54,433 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:36:54,433 > INFO > Collecting amp status... 
2020-07-09 12:36:54,762 > INFO > Collecting amp status Success.....
2020-07-09 12:36:55,274 > INFO > Post accepted by server
2020-07-09 12:36:55,274 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:37:55,275 > INFO > Collecting amp status... 
2020-07-09 12:37:55,538 > INFO > Collecting amp status Success.....
2020-07-09 12:37:56,054 > INFO > Post accepted by server
2020-07-09 12:37:56,055 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:38:56,056 > INFO > Collecting amp status... 
2020-07-09 12:38:56,341 > INFO > Collecting amp status Success.....
2020-07-09 12:38:56,852 > INFO > Post accepted by server
2020-07-09 12:38:56,852 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:39:56,853 > INFO > Collecting amp status... 
2020-07-09 12:39:57,168 > INFO > Collecting amp status Success.....
2020-07-09 12:39:57,668 > INFO > Post accepted by server
2020-07-09 12:39:57,668 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:40:57,668 > INFO > Collecting amp status... 
2020-07-09 12:40:57,947 > INFO > Collecting amp status Success.....
2020-07-09 12:40:58,466 > INFO > Post accepted by server
2020-07-09 12:40:58,467 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:41:58,467 > INFO > Collecting amp status... 
2020-07-09 12:41:58,787 > INFO > Collecting amp status Success.....
2020-07-09 12:41:59,299 > INFO > Post accepted by server
2020-07-09 12:41:59,300 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:56:40,022 > INFO > 
 =================== Starting Airwave Agent ======================== 

2020-07-09 12:56:40,023 > INFO > Starting Airwave Agent...
2020-07-09 12:56:49,748 > INFO > Login success
2020-07-09 12:56:49,749 > INFO > Collecting amp status... 
2020-07-09 12:56:50,618 > INFO > Collecting amp status Success.....
2020-07-09 12:56:59,541 > INFO > Post accepted by server
2020-07-09 12:56:59,542 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:57:59,544 > INFO > Collecting amp status... 
2020-07-09 12:58:00,358 > INFO > Collecting amp status Success.....
2020-07-09 12:58:01,969 > INFO > Post accepted by server
2020-07-09 12:58:01,969 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 12:59:01,971 > INFO > Collecting amp status... 
2020-07-09 12:59:02,744 > INFO > Collecting amp status Success.....
2020-07-09 12:59:08,462 > INFO > Post accepted by server
2020-07-09 12:59:08,463 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 13:00:08,463 > INFO > Collecting amp status... 
2020-07-09 13:00:11,605 > INFO > Collecting amp status Success.....
2020-07-09 13:00:13,002 > INFO > Post accepted by server
2020-07-09 13:00:13,002 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 13:01:13,003 > INFO > Collecting amp status... 
2020-07-09 13:01:13,673 > INFO > Collecting amp status Success.....
2020-07-09 13:01:15,164 > INFO > Post accepted by server
2020-07-09 13:01:15,164 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 13:02:15,164 > INFO > Collecting amp status... 
2020-07-09 13:02:18,402 > INFO > Collecting amp status Success.....
2020-07-09 13:02:26,713 > INFO > Post accepted by server
2020-07-09 13:02:26,714 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 13:03:26,716 > INFO > Collecting amp status... 
2020-07-09 13:03:30,280 > INFO > Collecting amp status Success.....
2020-07-09 13:03:32,046 > INFO > Post accepted by server
2020-07-09 13:03:32,046 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 13:04:32,047 > INFO > Collecting amp status... 
2020-07-09 13:04:32,796 > INFO > Collecting amp status Success.....
2020-07-09 13:04:34,628 > ERROR > post_to_server
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "d:\scripts\py\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\scripts\py\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\scripts\py\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\scripts\py\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "d:\scripts\py\lib\http\client.py", line 956, in send
    self.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001CB8B697128>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='server2.webr-env01.xyz', port=80): Max retries exceeded with url: /portal/collect_api/air_post (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB8B697128>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 93, in post_to_server
    res = requests.post(url, files=files)
  File "d:\scripts\py\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='server2.webr-env01.xyz', port=80): Max retries exceeded with url: /portal/collect_api/air_post (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB8B697128>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2020-07-09 13:04:34,960 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:30:26,656 > INFO > 
 =================== Starting Airwave Agent ======================== 

2020-07-09 17:30:26,656 > INFO > Starting Airwave Agent...
2020-07-09 17:30:47,679 > ERROR > airwave_login
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017BAC76AC88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BAC76AC88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 52, in airwave_login
    res = self.air_session.post(login_url, data = login_post,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BAC76AC88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 17:30:47,705 > WARNING > Login failed: trying after 30 sec
2020-07-09 17:31:38,716 > ERROR > airwave_login
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017BAC76AEB8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BAC76AEB8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 52, in airwave_login
    res = self.air_session.post(login_url, data = login_post,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BAC76AEB8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 17:31:38,720 > WARNING > Login failed: trying after 30 sec
2020-07-09 17:32:10,230 > INFO > Login success
2020-07-09 17:32:10,231 > INFO > Collecting amp status... 
2020-07-09 17:32:10,520 > INFO > Collecting amp status Success.....
2020-07-09 17:32:11,654 > INFO > Post accepted by server
2020-07-09 17:32:11,654 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:33:11,655 > INFO > Collecting amp status... 
2020-07-09 17:33:11,949 > INFO > Collecting amp status Success.....
2020-07-09 17:33:12,452 > INFO > Post accepted by server
2020-07-09 17:33:12,453 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:34:12,453 > INFO > Collecting amp status... 
2020-07-09 17:34:12,757 > INFO > Collecting amp status Success.....
2020-07-09 17:34:13,269 > INFO > Post accepted by server
2020-07-09 17:34:13,269 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:35:13,270 > INFO > Collecting amp status... 
2020-07-09 17:35:13,575 > INFO > Collecting amp status Success.....
2020-07-09 17:35:14,095 > INFO > Post accepted by server
2020-07-09 17:35:14,096 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:36:14,096 > INFO > Collecting amp status... 
2020-07-09 17:36:14,385 > INFO > Collecting amp status Success.....
2020-07-09 17:36:14,913 > INFO > Post accepted by server
2020-07-09 17:36:14,914 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:37:14,914 > INFO > Collecting amp status... 
2020-07-09 17:37:15,230 > INFO > Collecting amp status Success.....
2020-07-09 17:37:15,754 > INFO > Post accepted by server
2020-07-09 17:37:15,755 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:38:15,755 > INFO > Collecting amp status... 
2020-07-09 17:38:16,037 > INFO > Collecting amp status Success.....
2020-07-09 17:38:16,572 > INFO > Post accepted by server
2020-07-09 17:38:16,572 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:39:16,573 > INFO > Collecting amp status... 
2020-07-09 17:39:16,850 > INFO > Collecting amp status Success.....
2020-07-09 17:39:17,376 > INFO > Post accepted by server
2020-07-09 17:39:17,376 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:40:17,377 > INFO > Collecting amp status... 
2020-07-09 17:40:17,655 > INFO > Collecting amp status Success.....
2020-07-09 17:40:18,184 > INFO > Post accepted by server
2020-07-09 17:40:18,186 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:41:18,187 > INFO > Collecting amp status... 
2020-07-09 17:41:18,480 > INFO > Collecting amp status Success.....
2020-07-09 17:41:19,010 > INFO > Post accepted by server
2020-07-09 17:41:19,011 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:42:19,011 > INFO > Collecting amp status... 
2020-07-09 17:42:19,289 > INFO > Collecting amp status Success.....
2020-07-09 17:42:19,799 > INFO > Post accepted by server
2020-07-09 17:42:19,800 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:43:19,800 > INFO > Collecting amp status... 
2020-07-09 17:43:20,121 > INFO > Collecting amp status Success.....
2020-07-09 17:43:20,658 > INFO > Post accepted by server
2020-07-09 17:43:20,658 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:44:20,659 > INFO > Collecting amp status... 
2020-07-09 17:44:20,976 > INFO > Collecting amp status Success.....
2020-07-09 17:44:21,500 > INFO > Post accepted by server
2020-07-09 17:44:21,502 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:45:21,503 > INFO > Collecting amp status... 
2020-07-09 17:45:21,788 > INFO > Collecting amp status Success.....
2020-07-09 17:45:22,308 > INFO > Post accepted by server
2020-07-09 17:45:22,308 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:46:22,309 > INFO > Collecting amp status... 
2020-07-09 17:46:22,618 > INFO > Collecting amp status Success.....
2020-07-09 17:46:23,127 > INFO > Post accepted by server
2020-07-09 17:46:23,128 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:47:23,128 > INFO > Collecting amp status... 
2020-07-09 17:47:23,408 > INFO > Collecting amp status Success.....
2020-07-09 17:47:23,932 > INFO > Post accepted by server
2020-07-09 17:47:23,932 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:48:23,932 > INFO > Collecting amp status... 
2020-07-09 17:48:24,242 > INFO > Collecting amp status Success.....
2020-07-09 17:48:24,751 > INFO > Post accepted by server
2020-07-09 17:48:24,751 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:49:24,751 > INFO > Collecting amp status... 
2020-07-09 17:49:25,041 > INFO > Collecting amp status Success.....
2020-07-09 17:49:25,548 > INFO > Post accepted by server
2020-07-09 17:49:25,549 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:50:25,549 > INFO > Collecting amp status... 
2020-07-09 17:50:25,839 > INFO > Collecting amp status Success.....
2020-07-09 17:50:26,355 > INFO > Post accepted by server
2020-07-09 17:50:26,356 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:51:26,356 > INFO > Collecting amp status... 
2020-07-09 17:51:26,631 > INFO > Collecting amp status Success.....
2020-07-09 17:51:27,161 > INFO > Post accepted by server
2020-07-09 17:51:27,162 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:52:27,163 > INFO > Collecting amp status... 
2020-07-09 17:52:27,475 > INFO > Collecting amp status Success.....
2020-07-09 17:52:28,004 > INFO > Post accepted by server
2020-07-09 17:52:28,005 > INFO > Sleeping (60 sec) for next collection 
2020-07-09 17:53:28,006 > INFO > Collecting amp status... 
2020-07-09 17:53:28,273 > INFO > Collecting amp status Success.....
2020-07-09 17:53:28,784 > INFO > Post accepted by server
2020-07-09 17:53:28,785 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:12:32,073 > INFO > 
 =================== Starting Airwave Agent ======================== 

2020-07-11 09:12:32,080 > INFO > Starting Airwave Agent...
2020-07-11 09:12:53,093 > ERROR > airwave_login
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 52, in airwave_login
    res = self.air_session.post(login_url, data = login_post,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /LOGIN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-11 09:12:53,178 > WARNING > Login failed: trying after 30 sec
2020-07-11 09:13:26,648 > INFO > Login success
2020-07-11 09:13:26,648 > INFO > Collecting amp status... 
2020-07-11 09:13:27,074 > INFO > Collecting amp status Success.....
2020-07-11 09:13:28,214 > INFO > Post accepted by server
2020-07-11 09:13:28,215 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:14:28,215 > INFO > Collecting amp status... 
2020-07-11 09:14:28,638 > INFO > Collecting amp status Success.....
2020-07-11 09:14:29,419 > INFO > Post accepted by server
2020-07-11 09:14:29,419 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:15:29,420 > INFO > Collecting amp status... 
2020-07-11 09:15:30,624 > INFO > Collecting amp status Success.....
2020-07-11 09:15:31,396 > INFO > Post accepted by server
2020-07-11 09:15:31,396 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:16:31,397 > INFO > Collecting amp status... 
2020-07-11 09:16:31,811 > INFO > Collecting amp status Success.....
2020-07-11 09:16:32,581 > INFO > Post accepted by server
2020-07-11 09:16:32,581 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:17:32,581 > INFO > Collecting amp status... 
2020-07-11 09:17:33,012 > INFO > Collecting amp status Success.....
2020-07-11 09:17:33,800 > INFO > Post accepted by server
2020-07-11 09:17:33,801 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:18:33,802 > INFO > Collecting amp status... 
2020-07-11 09:18:34,261 > INFO > Collecting amp status Success.....
2020-07-11 09:18:35,037 > INFO > Post accepted by server
2020-07-11 09:18:35,037 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:19:35,038 > INFO > Collecting amp status... 
2020-07-11 09:19:35,452 > INFO > Collecting amp status Success.....
2020-07-11 09:19:36,234 > INFO > Post accepted by server
2020-07-11 09:19:36,235 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:20:36,236 > INFO > Collecting amp status... 
2020-07-11 09:20:36,673 > INFO > Collecting amp status Success.....
2020-07-11 09:20:37,464 > INFO > Post accepted by server
2020-07-11 09:20:37,465 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:21:37,466 > INFO > Collecting amp status... 
2020-07-11 09:21:37,871 > INFO > Collecting amp status Success.....
2020-07-11 09:21:38,653 > INFO > Post accepted by server
2020-07-11 09:21:38,654 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:22:38,654 > INFO > Collecting amp status... 
2020-07-11 09:22:39,078 > INFO > Collecting amp status Success.....
2020-07-11 09:22:40,855 > INFO > Post accepted by server
2020-07-11 09:22:40,856 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:23:40,857 > INFO > Collecting amp status... 
2020-07-11 09:23:41,261 > INFO > Collecting amp status Success.....
2020-07-11 09:23:42,044 > INFO > Post accepted by server
2020-07-11 09:23:42,045 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:24:42,046 > INFO > Collecting amp status... 
2020-07-11 09:24:42,451 > INFO > Collecting amp status Success.....
2020-07-11 09:24:43,233 > INFO > Post accepted by server
2020-07-11 09:24:43,233 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:25:43,234 > INFO > Collecting amp status... 
2020-07-11 09:25:44,247 > INFO > Collecting amp status Success.....
2020-07-11 09:25:45,040 > INFO > Post accepted by server
2020-07-11 09:25:45,041 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:26:45,041 > INFO > Collecting amp status... 
2020-07-11 09:26:45,461 > INFO > Collecting amp status Success.....
2020-07-11 09:26:46,242 > INFO > Post accepted by server
2020-07-11 09:26:46,243 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:27:46,243 > INFO > Collecting amp status... 
2020-07-11 09:27:46,655 > INFO > Collecting amp status Success.....
2020-07-11 09:27:47,443 > INFO > Post accepted by server
2020-07-11 09:27:47,443 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:28:47,443 > INFO > Collecting amp status... 
2020-07-11 09:28:48,761 > INFO > Collecting amp status Success.....
2020-07-11 09:28:49,534 > INFO > Post accepted by server
2020-07-11 09:28:49,534 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:29:49,535 > INFO > Collecting amp status... 
2020-07-11 09:29:49,992 > INFO > Collecting amp status Success.....
2020-07-11 09:29:50,766 > INFO > Post accepted by server
2020-07-11 09:29:50,767 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:30:50,768 > INFO > Collecting amp status... 
2020-07-11 09:30:51,172 > INFO > Collecting amp status Success.....
2020-07-11 09:30:51,945 > INFO > Post accepted by server
2020-07-11 09:30:51,946 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:31:51,946 > INFO > Collecting amp status... 
2020-07-11 09:31:52,367 > INFO > Collecting amp status Success.....
2020-07-11 09:31:53,156 > INFO > Post accepted by server
2020-07-11 09:31:53,157 > INFO > Sleeping (60 sec) for next collection 
2020-07-11 09:32:53,158 > INFO > Collecting amp status... 
2020-07-11 09:33:23,853 > ERROR > collect_ap_status
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "d:\scripts\py\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "d:\scripts\py\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "d:\scripts\py\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "d:\scripts\py\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "d:\scripts\py\lib\ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "d:\scripts\py\lib\ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "d:\scripts\py\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "d:\scripts\py\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "d:\scripts\py\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "d:\scripts\py\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "d:\scripts\py\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "d:\scripts\py\lib\ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "d:\scripts\py\lib\ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 67, in collect_amp_status
    res = self.air_session.get(url,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
2020-07-11 09:33:23,938 > ERROR > unknown issue , sleeping 30 sec
2020-07-11 09:33:53,938 > INFO > Collecting amp status... 
2020-07-11 09:34:01,605 > ERROR > collect_ap_status
Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\scripts\py\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "d:\scripts\py\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\scripts\py\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "d:\scripts\py\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /amp_stats.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Airwave_Agent.py", line 67, in collect_amp_status
    res = self.air_session.get(url,verify=False)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\scripts\py\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\scripts\py\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.17.84.20', port=443): Max retries exceeded with url: /amp_stats.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000145499E0BA8>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2020-07-11 09:34:01,608 > ERROR > unknown issue , sleeping 30 sec
